//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 08:45:13 AM CET 
//


package jav.correctionBackend.alto1_4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jav.correctionBackend.alto1_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jav.correctionBackend.alto1_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Alto1_4Document }
     * 
     */
    public Alto1_4Document createAlto() {
        return new Alto1_4Document();
    }

    /**
     * Create an instance of {@link StringType }
     * 
     */
    public StringType createStringType() {
        return new StringType();
    }

    /**
     * Create an instance of {@link TextBlockType }
     * 
     */
    public TextBlockType createTextBlockType() {
        return new TextBlockType();
    }

    /**
     * Create an instance of {@link TextBlockType.TextLine }
     * 
     */
    public TextBlockType.TextLine createTextBlockTypeTextLine() {
        return new TextBlockType.TextLine();
    }

    /**
     * Create an instance of {@link Alto.Layout }
     * 
     */
    public Alto1_4Document.Layout createAltoLayout() {
        return new Alto1_4Document.Layout();
    }

    /**
     * Create an instance of {@link Alto.Styles }
     * 
     */
    public Alto1_4Document.Styles createAltoStyles() {
        return new Alto1_4Document.Styles();
    }

    /**
     * Create an instance of {@link Alto.Description }
     * 
     */
    public Alto1_4Document.Description createAltoDescription() {
        return new Alto1_4Document.Description();
    }

    /**
     * Create an instance of {@link ProcessingStepType }
     * 
     */
    public ProcessingStepType createProcessingStepType() {
        return new ProcessingStepType();
    }

    /**
     * Create an instance of {@link ShapeType }
     * 
     */
    public ShapeType createShapeType() {
        return new ShapeType();
    }

    /**
     * Create an instance of {@link ProcessingSoftwareType }
     * 
     */
    public ProcessingSoftwareType createProcessingSoftwareType() {
        return new ProcessingSoftwareType();
    }

    /**
     * Create an instance of {@link OcrProcessingType }
     * 
     */
    public OcrProcessingType createOcrProcessingType() {
        return new OcrProcessingType();
    }

    /**
     * Create an instance of {@link EllipseType }
     * 
     */
    public EllipseType createEllipseType() {
        return new EllipseType();
    }

    /**
     * Create an instance of {@link SourceImageInformationType }
     * 
     */
    public SourceImageInformationType createSourceImageInformationType() {
        return new SourceImageInformationType();
    }

    /**
     * Create an instance of {@link CircleType }
     * 
     */
    public CircleType createCircleType() {
        return new CircleType();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link FileIdentifierType }
     * 
     */
    public FileIdentifierType createFileIdentifierType() {
        return new FileIdentifierType();
    }

    /**
     * Create an instance of {@link GraphicalElementType }
     * 
     */
    public GraphicalElementType createGraphicalElementType() {
        return new GraphicalElementType();
    }

    /**
     * Create an instance of {@link ComposedBlockType }
     * 
     */
    public ComposedBlockType createComposedBlockType() {
        return new ComposedBlockType();
    }

    /**
     * Create an instance of {@link BlockType }
     * 
     */
    public BlockType createBlockType() {
        return new BlockType();
    }

    /**
     * Create an instance of {@link PageSpaceType }
     * 
     */
    public PageSpaceType createPageSpaceType() {
        return new PageSpaceType();
    }

    /**
     * Create an instance of {@link IllustrationType }
     * 
     */
    public IllustrationType createIllustrationType() {
        return new IllustrationType();
    }

    /**
     * Create an instance of {@link StringType.ALTERNATIVE }
     * 
     */
    public StringType.ALTERNATIVE createStringTypeALTERNATIVE() {
        return new StringType.ALTERNATIVE();
    }

    /**
     * Create an instance of {@link TextBlockType.TextLine.SP }
     * 
     */
    public TextBlockType.TextLine.SP createTextBlockTypeTextLineSP() {
        return new TextBlockType.TextLine.SP();
    }

    /**
     * Create an instance of {@link TextBlockType.TextLine.HYP }
     * 
     */
    public TextBlockType.TextLine.HYP createTextBlockTypeTextLineHYP() {
        return new TextBlockType.TextLine.HYP();
    }

    /**
     * Create an instance of {@link Alto.Layout.Page }
     * 
     */
    public Alto1_4Document.Layout.Page createAltoLayoutPage() {
        return new Alto1_4Document.Layout.Page();
    }

    /**
     * Create an instance of {@link Alto.Styles.TextStyle }
     * 
     */
    public Alto1_4Document.Styles.TextStyle createAltoStylesTextStyle() {
        return new Alto1_4Document.Styles.TextStyle();
    }

    /**
     * Create an instance of {@link Alto.Styles.ParagraphStyle }
     * 
     */
    public Alto1_4Document.Styles.ParagraphStyle createAltoStylesParagraphStyle() {
        return new Alto1_4Document.Styles.ParagraphStyle();
    }

    /**
     * Create an instance of {@link Alto.Description.OCRProcessing }
     * 
     */
    public Alto1_4Document.Description.OCRProcessing createAltoDescriptionOCRProcessing() {
        return new Alto1_4Document.Description.OCRProcessing();
    }

}
